EMACS ?= emacs
BATCH = $(EMACS) -Q --batch
LOAD_PATH = -L lisp -L tests
SOURCE = lisp/emacs-boost-gptel.el
TESTS = tests/gptel-tools-test.el

.PHONY: all check tangle test compile clean

# Run the complete validation workflow.
all: check

# Tangle, test, and byte-compile the project.
check: tangle test compile

# Generate the Emacs Lisp file from README.org.
tangle:
	$(BATCH) --eval "(progn (require 'org) (require 'ob-tangle) (org-babel-tangle-file \"README.org\"))"

# Run the ERT test suite.
test: tangle
	$(BATCH) $(LOAD_PATH) -l $(TESTS) -f ert-run-tests-batch-and-exit

# Byte-compile the generated Emacs Lisp file.
compile: tangle
	$(BATCH) $(LOAD_PATH) --eval "(progn (require 'emacs-boost-gptel) (byte-compile-file \"$(SOURCE)\"))"

# Remove generated byte-compiled files.
clean:
	rm -f lisp/*.elc tests/*.elc
